export const Data = [
  {
    id: "1",
    ProjectName: "HTML Fundamentals",
    scores: "100",
    InternName: "Musa Bello",
    Submits: 100,
    performance: "Excellent",
    position: "1st",
    profile: "Images/profile1.jpeg",
  },

  {
    id: "2",
    ProjectName: "HTML Semantics",
    scores: "67",
    InternName: "Adamu Charles",
    Submits: "25",
    performance: "Credit",
    position: "5th",
    profile: "Images/profile2.jpeg",
  },

  {
    id: "3",
    ProjectName: "HTML Attributes",
    scores: "85",
    InternName: "Okechukwu John",
    Submits: "83",
    performance: "Excellent",
    position: "3rd",
    profile: "Images/profile3.jpeg",
  },

  {
    id: "4",
    ProjectName: "Advanced CSS",
    scores: "70",
    InternName: "Nwangwu Chioma",
    Submits: "40",
    performance: "Pass",
    position: "15th",
    profile: "Images/profile4.jpeg",
  },

  {
    id: "5",
    ProjectName: "CSS Libraries",
    scores: "47",
    InternName: "Ibrahim Joseph",
    Submits: "20",
    performance: "Pass",
    position: "20th",
    profile: "Images/profile5.jpeg",
  },
  {
    id: "6",
    ProjectName: "CSS Background Properties",
    scores: "90",
    InternName: "Onyeka Ifechukwu",
    Submits: "80",
    performance: "Excellent",
    position: "2nd",
    profile: "Images/profile6.jpeg",
  },

  {
    id: "7",
    ProjectName: "Basic JavaScript",
    scores: "70",
    InternName: "Okoh Nkechi",
    Submits: "57",
    performance: "Credit",
    position: "4th",
    profile: "Images/profile7.jpeg",
  },

  {
    id: "8",
    ProjectName: "JavaScript Arrays & Objects",
    scores: "79",
    InternName: "Ifeanyi Onyeka",
    Submits: "78",
    performance: "credit",
    position: "6th",
    profile: "Images/profile8.jpeg",
  },

  {
    id: "9",
    ProjectName: "JavaScript Conditional Rendering",
    scores: "65",
    InternName: "Emerie Ozokoye",
    Submits: "75",
    performance: "Credit",
    position: "7th",
    profile: "Images/profile9.jpeg",
  },

  {
    id: "10",
    ProjectName: "JavaScript Map,Filter,Splice...",
    scores: "57",
    InternName: "Ololade Efe",
    Submits: "37",
    performance: "Pass",
    position: "12th",
    profile: "Images/profile10.jpeg",
  },

  {
    id: "11",
    ProjectName: "React",
    scores: "80",
    InternName: "Ogalla Ikechukwu",
    Submits: "60",
    performance: "distinction",
    position: "9th",
    profile: "Images/profile11.jpeg",
  },
];
